import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import ForFun from '@/components/ForFrun'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  async function connectHandler(){
    const res = await fetch('/api/connect');
    const data = await res.json()
    // await alert(data.name)
  }

  return (
    <>
      <Head>
        <title>To The Moon:부자됩시다</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <main className={styles.main}>
        <h1>To The Moon Home Page</h1>
        <ForFun></ForFun>
        
        <h2>뭘 넣을지 같이 고민해봅시다~</h2>
      </main>
    </>
  )
}
