import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import ForFun from "@/components/ForFrun";
import InvestmentSummaryComponent from "@/components/InvestmentSummaryComponent";
import InvestmentCardComponent from "@/components/InvestmentCardComponent";
import { ChangeEvent, useEffect, useState } from "react";

import BottomNavigation from "@/components/BottomNavigation";

import TopTitle from "@/components/TopTitle";
import { numberWithCommas } from "@/library/string";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [wallet, setWallet] = useState<any>(undefined);
  const [bitcoin, setBitcoin] = useState(0);
  const [etherium, setEtherium] = useState(0);
  const [number, setNumber] = useState(0);

  useEffect(() => {
    const fetchData = async () => {
      const data_res = await fetch("/api/wallet/1");
      const bitcoin_res = await fetch(`/api/price/BTC`);
      const ether_res = await fetch(`/api/price/ETC`);

      const data = await data_res.json();
      const bit = await bitcoin_res.json();
      const ether = await ether_res.json();

      console.log(data);
      setWallet(data);
      setBitcoin(Number(bit.price));
      setEtherium(Number(ether.price));
    };
    fetchData();
  }, []);

  function handleChange(e:any) {
    setNumber(e.target?.value)
  }

  async function handleBuy() {
    await fetch('api/order', {
        method:"POST",
        body:JSON.stringify({
            "user_id": 1,
            "type": 'buy',
            'coin_num':Number(number)
        })
    })
  }

  async function handleSell() {
    console.log('handle Sell')
    const response = await fetch('api/order', {
        method:"POST",
        body:JSON.stringify({
            "user_id": 1,
            "type": 'sell',
            'coin_num':Number(number)
        })
    })
    console.log(response)
  }

  return (
    <>
      <Head>
        <title>To The Moon:부자됩시다</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar/> */}

      <main className={styles.main}>
        <TopTitle />

        <br />

        <InvestmentSummaryComponent
          total={wallet?.total}
          coin={wallet?.bitcoin}
          cash={wallet?.cash}
        />

        <br />

        <div>
          <h3>현재 비트코인 시세</h3>
          <h2>₩ {numberWithCommas(bitcoin)}</h2>
        </div>

        <input type="text" onChange={handleChange}/>
        <p>{number}</p>
        <div>
          <button onClick={handleBuy}>buy</button>
          <button onClick={handleSell}>sell</button>
        </div>

        <BottomNavigation />
        {/* <ForFun></ForFun> */}
      </main>
    </>
  );
}
